name: "Install Theos"
description: "Install Theos and prepare it for building projects"
author: "Randomblock1"
branding:
  icon: download-cloud
  color: purple

inputs:
  theos-dir:
    description: "Where to install Theos"
    required: false
    default: ${{ github.workspace }}/theos
  theos-src:
    description: "Where to clone Theos from (git URL)"
    required: false
    default: "https://github.com/theos/theos"
  theos-sdks:
    description: "Where to clone the iOS SDKs from (GitHub repository URL)"
    required: false
    default: "https://github.com/theos/sdks"
  theos-sdks-branch:
    description: "Which branch to clone from SDK repo"
    required: false
    default: "master"
  orion:
    description: "Whether to enable Orion, which adds support for Swift tweaks"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup (MacOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install ldid make
        PATH="$(brew --prefix make)/libexec/gnubin:$PATH" >> $GITHUB_ENV

    - name: Setup (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: sudo apt install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libplist-utils

    - name: Setup environment
      shell: bash
      run: echo "THEOS=${{ inputs.theos-dir }}" >> $GITHUB_ENV

    - name: Download Theos
      shell: bash
      run: |
        if [ ! -d "${{ inputs.theos-dir }}" ]; then
          git clone ${{ inputs.theos-src }} ${{ inputs.theos-dir }} --recursive
          echo "Theos successfully downloaded."
        else
          echo "Theos already cached."
        fi

    - name: Get toolchain (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        if [[ "$(ls ${{ inputs.theos-dir }}/sdks)" ]]; then
          echo "Linux toolchain already cached, skipping..."
        else
          TMP_DL=$(mktemp -d)
          wget --no-verbose https://github.com/kabiroberai/swift-toolchain-linux/releases/download/v2.3.0/swift-5.8-ubuntu22.04.tar.xz -P $TMP_DL
          tar -xvf $TMP_DL/swift-5.8-ubuntu22.04.tar.xz -C $THEOS/toolchain
          rm -Rf $TMP_DL
        fi

    - name: Get SDKs
      shell: bash
      run: |
        if [[ "$(ls ${{ inputs.theos-dir }}/sdks)" ]]; then
          echo "Theos SDKs already cached, skipping..."
        else
          cd ${{ inputs.theos-dir }}/sdks
          wget --no-verbose ${{ inputs.theos-sdks }}/archive/${{ inputs.theos-sdks-branch }}.zip
          TMP=$(mktemp -d)
          7z x ${{ inputs.theos-sdks-branch }}.zip -o$TMP
          mv $TMP/*-${{ inputs.theos-sdks-branch }}/*.sdk $THEOS/sdks
          rm -r ${{ inputs.theos-sdks-branch }}.zip $TMP
        fi

    - name: Enable Orion
      shell: bash
      if: inputs.orion == 'true'
      run: |
        cd ${{ inputs.theos-dir }}
        git fetch
        git checkout orion
        git submodule update --init
